// Generated by CoffeeScript 1.8.0
(function() {
  var i, _i;

  this.autowatch = 1;

  this.myWindow = new JitterObject("jit.window", "WINDOW");

  this.myNode = new JitterObject("jit.gl.node", "WINDOW");

  this.myNode.name = "NODE";

  this.myRender = new JitterObject("jit.gl.render", "WINDOW");

  this.myTexts = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 9; i = ++_i) {
      _results.push(new JitterObject("jit.gl.text", "NODE"));
    }
    return _results;
  })();

  for (i = _i = 0; _i <= 9; i = ++_i) {
    this.myTexts[i].text("Hello " + i);
  }

  this.myRender = myRender;

  this.bang = function() {
    this.myRender.erase();
    this.myRender.drawclients();
    return this.myRender.swap();
  };

  post(new Date + "\n");

}).call(this);
